// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn_LXCGBbyvnHhumFLHMOumqB8Z6Lbdtc',
    appId: '1:340756057854:web:7b3cc2160cffa0add4dfaf',
    messagingSenderId: '340756057854',
    projectId: 'chat-app-baf2d',
    authDomain: 'chat-app-baf2d.firebaseapp.com',
    storageBucket: 'chat-app-baf2d.firebasestorage.app',
    measurementId: 'G-DPNMVBGYS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ua_mCW1HIahPBrYMqWA1VL9Y1h_5ADo',
    appId: '1:340756057854:android:a6f39aebbc0e9b08d4dfaf',
    messagingSenderId: '340756057854',
    projectId: 'chat-app-baf2d',
    storageBucket: 'chat-app-baf2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3C6g9FAS8Bd3vLBu5nWRKanGuLrlhXY4',
    appId: '1:340756057854:ios:13c4d490dee8cd1fd4dfaf',
    messagingSenderId: '340756057854',
    projectId: 'chat-app-baf2d',
    storageBucket: 'chat-app-baf2d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3C6g9FAS8Bd3vLBu5nWRKanGuLrlhXY4',
    appId: '1:340756057854:ios:13c4d490dee8cd1fd4dfaf',
    messagingSenderId: '340756057854',
    projectId: 'chat-app-baf2d',
    storageBucket: 'chat-app-baf2d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn_LXCGBbyvnHhumFLHMOumqB8Z6Lbdtc',
    appId: '1:340756057854:web:a4de66aee1d59278d4dfaf',
    messagingSenderId: '340756057854',
    projectId: 'chat-app-baf2d',
    authDomain: 'chat-app-baf2d.firebaseapp.com',
    storageBucket: 'chat-app-baf2d.firebasestorage.app',
    measurementId: 'G-NW8PPZP00N',
  );
}
